version: '3.8'

services:
  test-postgress-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=twitter_clone_phoenix_tutorial_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432